<?xml version="1.0" encoding="utf-8"?><Database Name="Blackhole" Class="BlackholeDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Blackhole;Integrated Security=True" SettingsObjectName="Blackhole.Server.My.MySettings" SettingsPropertyName="BlackholeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="NODE" Member="NODEs">
    <Type Name="NODE">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="metadata" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="QUAD" Member="QUADs">
    <Type Name="QUAD">
      <Column Name="subject" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="predicate" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="object" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="graph" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="s25p5o1type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>